<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Requirements" nsURI="http://www.polarsys.org/kitalpha/requirements"
    nsPrefix="Requirements">
  <eClassifiers xsi:type="ecore:EClass" name="ReqIFElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReqIF_Identifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRelation" abstract="true" eSuperTypes="#//ReqIFElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationType" eType="#//RelationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReqIF_RelationType" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalRelation" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//ReqIFElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//AttributeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValueAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValueAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeOwner" abstract="true" eSuperTypes="#//ReqIFElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//AttributeOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementType" eType="#//RequirementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRelations" upperBound="-1"
        eType="#//AbstractRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReqIF_ChapterName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReqIF_ForeignID" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReqIF_Prefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReqIF_Text" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRequirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//AttributeOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleType" eType="#//ModuleType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRequirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypesFolder" eSuperTypes="#//ReqIFElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefinitionTypes" upperBound="-1"
        eType="#//DataTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTypes" upperBound="-1"
        eType="#//AbstractType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType" abstract="true" eSuperTypes="#//ReqIFElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttributes" upperBound="-1"
        eType="#//AttributeDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleType" eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementType" eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationType" eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeDefinition" eSuperTypes="#//ReqIFElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDefinition" eSuperTypes="#//ReqIFElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionType" eType="#//DataTypeDefinition"/>
  </eClassifiers>
</ecore:EPackage>
